import {flushSync} from 'react-dom';
import {registerAtlasTools} from './agent-tools';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowUpRight,ChevronRight,Focus,Info,Layers3,Pause,RotateCcw,RotateCw,Search,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import AnatomyScene from './scene';
import {DEFAULT_VISIBLE,SYSTEMS,EXPLANATIONS,explanation,type Atlas,type Concept,type SceneState,type SystemId,type View} from './anatomy';
import {SYSTEM_EN,anatomySearchText,displayAnatomyName,zhAnatomyName} from './i18n';
const initial:SceneState={explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0};
export default function Home(){
 const detailTitle=useRef<HTMLHeadingElement>(null);
 const [atlas,setAtlas]=useState<Atlas|null>(null),[state,setState]=useState(initial),[progress,setProgress]=useState(0),[error,setError]=useState(''),[panel,setPanel]=useState<'layers'|'search'|null>(null),[details,setDetails]=useState(false),[about,setAbout]=useState(false),[query,setQuery]=useState(''),[chosen,setChosen]=useState<Concept|null>(null);
 useEffect(()=>{const abort=new AbortController();setProgress(0);setError('');setAtlas(null);setChosen(null);setDetails(false);setState({...initial,visible:DEFAULT_VISIBLE});fetch(`${import.meta.env.BASE_URL}models/atlas.json`,{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('无法加载解剖目录。');return r.json();}).then(data=>setAtlas(data as Atlas)).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setPanel('search');setDetails(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const counts=useMemo(()=>Object.fromEntries(SYSTEMS.map(s=>[s.id,atlas?.parts.filter(p=>p.system===s.id).length??0])),[atlas]);
 const activeSystems=SYSTEMS.filter(s=>counts[s.id]>0);
 const selectedParts=state.selected.map(id=>parts.get(id)).filter(p=>!!p),selected=selectedParts[0],system=SYSTEMS.find(s=>s.id===selected?.system);
 const visibleCount=atlas?.parts.filter(p=>state.isolate?state.selected.includes(p.id):state.visible.includes(p.system)||state.selected.includes(p.id)).length??0;
 const results=useMemo(()=>{if(!atlas)return[];const term=query.toLowerCase().trim();if(!term)return ['heart','brain','liver','stomach','spleen','pancreas','urinary bladder','trachea'].map(name=>atlas.concepts.find(c=>c.name.toLowerCase()===name)).filter((x):x is Concept=>!!x);return atlas.concepts.filter(c=>anatomySearchText(c.name).includes(term)||c.id.toLowerCase().includes(term)).sort((a,b)=>(zhAnatomyName(a.name)?0:1)-(zhAnatomyName(b.name)?0:1)||a.name.length-b.name.length).slice(0,80);},[atlas,query]);
 const choose=(c:Concept)=>{setChosen(c);setState(s=>({...s,selected:c.elements,isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 useEffect(()=>{if(!atlas)return;return registerAtlasTools(atlas,c=>flushSync(()=>choose(c)));},[atlas]);
 const choosePart=(id:string)=>{const p=parts.get(id);if(!p)return;setChosen({id:p.conceptId,name:p.name,elements:[id]});setState(s=>({...s,selected:[id],isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 const toggle=(id:SystemId)=>{setDetails(false);setState(s=>({...s,selected:[],isolate:false,visible:s.visible.includes(id)?s.visible.filter(x=>x!==id):[...s.visible,id]}));};
 const reset=()=>{setState(s=>({...initial,visible:DEFAULT_VISIBLE,reset:s.reset+1}));setChosen(null);setDetails(false);setPanel(null);};
 const openPanel=(next:'layers'|'search')=>{setDetails(false);setPanel(p=>p===next?null:next);};
 return <main className="studio">
  {atlas&&<AnatomyScene atlas={atlas} state={{...state,inspectorOpen:details&&selectedParts.length>0}} onSelect={choosePart} onProgress={n=>{setProgress(n);if(n===100)setError('');}} onError={setError}/>}
  <div className="vignette"/>
  <header className="identity"><div className="eyebrow"><span className="status-dot"/> 交互式人体解剖</div><h1>人体解剖图谱<Badge variant="outline" className="edition">3D</Badge></h1><div className="identity-meta">{atlas?atlas.parts.length.toLocaleString():'2,234'} 个三维结构 <span>·</span> BodyParts3D</div></header>
  <nav className="top-actions" aria-label="浏览工具"><Button variant="ghost" className={panel==='search'?'active':''} onClick={()=>openPanel('search')} aria-label="搜索解剖结构"><Search size={18}/><span>查找结构</span><kbd>/</kbd></Button><Button variant="ghost" className="icon-button" aria-label="关于本图谱" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}><Info size={18}/></Button></nav>
  <section className={`layers-panel glass ${panel==='layers'?'mobile-open':''}`} aria-label="解剖系统">
   <div className="panel-heading"><span>系统</span><Button variant="ghost" className="mobile-only icon-button" onClick={()=>setPanel(null)} aria-label="关闭系统面板"><X size={18}/></Button><Badge variant="secondary" className="desktop-only small-number">{activeSystems.length}</Badge></div>
   <div className="layer-presets"><Button variant="ghost" aria-pressed={activeSystems.every(x=>state.visible.includes(x.id))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:activeSystems.map(x=>x.id)}))}>全部</Button><Button variant="ghost" aria-pressed={state.visible.length===1&&state.visible[0]==='skeletal'} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['skeletal']}))}>骨骼</Button><Button variant="ghost" aria-pressed={state.visible.length===6&&['cardiac','respiratory','digestive','urinary','endocrine','reproductive'].every(id=>state.visible.includes(id as SystemId))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['cardiac','respiratory','digestive','urinary','endocrine','reproductive']}))}>脏器</Button></div>
   <div className="system-list">{activeSystems.map(s=><div className={`system-row ${state.visible.includes(s.id)?'enabled':''}`} key={s.id}><Button variant="ghost" className="system-name" title={`仅显示${s.name}`} onClick={()=>setState(v=>({...v,visible:[s.id],isolate:false,selected:[]}))}><span className="system-dot" style={{background:s.color}}/><span className="system-label"><span>{s.name}</span><small>{SYSTEM_EN[s.id]}</small></span><span className="system-count">{counts[s.id]}</span></Button><Switch checked={state.visible.includes(s.id)} onCheckedChange={()=>toggle(s.id)} aria-label={`显示${s.name}`} /></div>)}</div>
   <div className="panel-foot"><span>{visibleCount.toLocaleString()} 个结构可见</span><Button variant="ghost" onClick={()=>setState(s=>({...s,visible:[],selected:[],isolate:false}))}>全部隐藏</Button></div>
  </section>
  {panel==='search'&&<section className="search-panel glass" aria-label="查找解剖结构"><div className="panel-heading"><span>查找结构</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label="关闭搜索"><X size={18}/></Button></div><Combobox<Concept> items={results} value={null} onValueChange={value=>{if(value)choose(value);}} inputValue={query} onInputValueChange={setQuery} itemToStringLabel={c=>displayAnatomyName(c.name)} filter={null} open onOpenChange={open=>{if(!open)setPanel(null);}}><ComboboxInput autoFocus placeholder="心脏、股骨、FMA编号或英文名…" aria-label="搜索解剖结构" showTrigger={false}/><ComboboxContent className="anatomy-search-results"><ComboboxEmpty>没有找到匹配的结构。</ComboboxEmpty><ComboboxList>{(c:Concept)=><ComboboxItem key={c.id} value={c}><span className="search-result-text"><span className="search-result-name">{displayAnatomyName(c.name)}</span>{zhAnatomyName(c.name)&&<small>{c.name}</small>}</span><span className="small-number">{c.elements.length} 个</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><p className="search-note">{query?'最多显示80个结果，可继续输入以缩小范围。':'可输入中文常用名、英文解剖名或 FMA 编号。'}</p></section>}
  <nav className="view-controls glass" aria-label="视角控制">{(['three-quarter','front','side','back'] as View[]).map((v,i)=><Button variant="ghost" key={v} className={state.view===v?'active':''} aria-pressed={state.view===v} disabled={state.explode>.8&&v!=='front'} onClick={()=>setState(s=>({...s,view:v,reset:s.reset+1,rotate:false}))} title={`${['斜前方','正面','侧面','背面'][i]}视图`} aria-label={`${['斜前方','正面','侧面','背面'][i]}视图`}><span>{['¾','F','S','B'][i]}</span></Button>)}<i/><Button variant="ghost" disabled={state.explode>=.4} aria-label={state.rotate?'暂停旋转':'自动旋转'} title="自动旋转" className={state.rotate?'active':''} onClick={()=>setState(s=>({...s,rotate:!s.rotate}))}>{state.rotate?<Pause size={17}/>:<RotateCw size={18}/>}</Button><Button variant="ghost" aria-label="重置视角和系统" title="重置" onClick={reset}><RotateCcw size={17}/></Button></nav>
  <div className="scene-caption"><span className="caption-line"/><span>{state.isolate?(chosen?displayAnatomyName(chosen.name):'已选结构'):state.explode>.95?'解剖结构总览':state.explode>.05?'分离结构':'成人男性参考解剖'}</span><span className="caption-line"/></div>
  <div className="bottom-dock glass"><Button variant="ghost" className="mobile-only dock-layers" onClick={()=>openPanel('layers')} aria-label="打开系统面板"><Layers3 size={20}/><span>系统</span></Button><div className="explode-control"><div className="explode-label"><label id="explode-label">分离解剖结构</label><output>{Math.round(state.explode*100)}<span>%</span></output></div><Slider aria-labelledby="explode-label" min={0} max={100} step={1} value={[state.explode*100]} onValueChange={v=>setState(s=>({...s,explode:(Array.isArray(v)?v[0]:v)/100,view:(Array.isArray(v)?v[0]:v)>80?'front':s.view,rotate:false}))}/><div className="slider-endpoints"><span>组装</span><span>完全分离</span></div></div><Button variant="ghost" className="dock-reset" onClick={reset} aria-label="组装并重置"><RotateCcw size={18}/><span>重置</span></Button></div>
  <footer className="studio-footer"><span>{state.explode>.8?'拖动平移':'拖动旋转'} <b>·</b> 双指缩放 <b>·</b> 点击查看</span><Button variant="ghost" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}>来源与致谢 <ArrowUpRight size={12}/></Button></footer>
  {progress<100&&!error&&<div className="loading glass" role="status"><Activity size={18}/><div><strong>正在准备解剖模型</strong><span>{progress}% · 正在加载 {atlas?.parts.length.toLocaleString()??'2,234'} 个结构</span><div className="loading-track"><i style={{width:`${progress}%`}}/></div></div></div>}
  {error&&<div className="loading glass error" role="alert"><p>{error}</p><Button variant="ghost" onClick={()=>location.reload()}>重新加载</Button></div>}
  <Sheet open={details&&selectedParts.length>0} modal={false} disablePointerDismissal onOpenChange={setDetails}><SheetContent initialFocus={detailTitle} className={`detail-sheet glass ${state.isolate?'is-isolated':''}`} showCloseButton={true}><div className="detail-header"><div className="detail-accent" style={{background:system?.color}}/><div className="eyebrow">{system?.name??'解剖结构'}</div><SheetTitle ref={detailTitle} tabIndex={-1} className="structure-title">{chosen?displayAnatomyName(chosen.name):''}</SheetTitle>{chosen&&zhAnatomyName(chosen.name)&&<div className="structure-en">{chosen.name}</div>}</div><div className="detail-scroll" key={`${chosen?.id}-${state.isolate}`}><SheetDescription className="structure-description">{chosen&&selected?explanation(chosen.name,selected.system):''}</SheetDescription>{chosen&&!EXPLANATIONS[chosen.name.toLowerCase()]&&<span className="context-note">系统概述 · 结构名称来自原始解剖数据</span>}<div className="structure-meta"><span>图谱编号<strong>{chosen?.id}</strong></span><span>已选结构数<strong>{state.selected.length.toLocaleString()}</strong></span></div>{selectedParts.length>1&&<div className="member-list"><h3>包含的结构</h3>{selectedParts.slice(0,50).map(p=><Button variant="ghost" key={p.id} onClick={()=>choosePart(p.id)}><span><b>{displayAnatomyName(p.name)}</b>{zhAnatomyName(p.name)&&<small>{p.name}</small>}</span><ChevronRight size={14}/></Button>)}{selectedParts.length>50&&<p>另有 {selectedParts.length-50} 个结构未展开显示。</p>}</div>}<a className="source-link" href="https://lifesciencedb.jp/bp3d/" target="_blank" rel="noreferrer">查看原始解剖数据 <ArrowUpRight size={14}/></a></div><div className="detail-actions"><Button className={`primary-action ${state.isolate?'active':''}`} onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))}><Focus size={18}/>{state.isolate?'显示周围结构':'单独显示该结构'}<ChevronRight size={16}/></Button><Button variant="ghost" className="secondary-action" onClick={()=>{setState(s=>({...s,selected:[],isolate:false}));setDetails(false);}}>清除选择</Button></div></SheetContent></Sheet>
  <Sheet open={about} onOpenChange={setAbout}><SheetContent className="about-sheet glass"><div className="eyebrow">来源与范围</div><SheetTitle className="structure-title">人体解剖图谱 · 中文初版</SheetTitle><SheetDescription>基于 BodyParts3D 成人男性参考解剖的交互式三维浏览器。</SheetDescription><div className="about-copy"><p><strong>成人男性 · BodyParts3D</strong><br/>包含 2,234 个独立三维网格和 3,432 个命名解剖概念。</p><p>中文 V1.0 先完成界面、15 个系统及常见结构的中英双语适配；尚未覆盖的细小结构保留原始英文名与 FMA 编号，避免未经校对的医学术语误译。</p><p>本参考模型不包含所有人体结构、个体差异或解剖变异。网页模型经过简化以适应浏览器性能。本工具仅供教学、学习和解剖参考，不用于诊断、手术导航或临床决策。</p><h3>数据来源与许可</h3><p>BodyParts3D, © The Database Center for Life Science，数据按 CC BY 4.0 许可使用；原 Human Atlas 应用代码按 MIT License 发布。中文界面和术语适配属于二次开发。</p><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/lic.html" target="_blank" rel="noreferrer">数据集许可 <ArrowUpRight size={14}/></a><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html" target="_blank" rel="noreferrer">原始几何与元数据 <ArrowUpRight size={14}/></a><a href="https://academic.oup.com/nar/article/37/suppl_1/D782/1000752" target="_blank" rel="noreferrer">BodyParts3D 原始论文 <ArrowUpRight size={14}/></a></div></SheetContent></Sheet>
 </main>;
}
